//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Password_Cs.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unchecked")]
        public global::System.Windows.Forms.CheckState CheckBox1 {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["CheckBox1"]));
            }
            set {
                this["CheckBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unchecked")]
        public global::System.Windows.Forms.CheckState CheckBox2 {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["CheckBox2"]));
            }
            set {
                this["CheckBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unchecked")]
        public global::System.Windows.Forms.CheckState CheckBox3 {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["CheckBox3"]));
            }
            set {
                this["CheckBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unchecked")]
        public global::System.Windows.Forms.CheckState CheckBox4 {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["CheckBox4"]));
            }
            set {
                this["CheckBox4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::MetroFramework.MetroColorStyle Style {
            get {
                return ((global::MetroFramework.MetroColorStyle)(this["Style"]));
            }
            set {
                this["Style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::MetroFramework.MetroColorStyle StyleTab {
            get {
                return ((global::MetroFramework.MetroColorStyle)(this["StyleTab"]));
            }
            set {
                this["StyleTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::MetroFramework.MetroColorStyle StyleCheck1 {
            get {
                return ((global::MetroFramework.MetroColorStyle)(this["StyleCheck1"]));
            }
            set {
                this["StyleCheck1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::MetroFramework.MetroColorStyle StyleCheck2 {
            get {
                return ((global::MetroFramework.MetroColorStyle)(this["StyleCheck2"]));
            }
            set {
                this["StyleCheck2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::MetroFramework.MetroColorStyle StyleCheck3 {
            get {
                return ((global::MetroFramework.MetroColorStyle)(this["StyleCheck3"]));
            }
            set {
                this["StyleCheck3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::MetroFramework.MetroColorStyle StyleCheck4 {
            get {
                return ((global::MetroFramework.MetroColorStyle)(this["StyleCheck4"]));
            }
            set {
                this["StyleCheck4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::MetroFramework.MetroColorStyle StyleCombo1 {
            get {
                return ((global::MetroFramework.MetroColorStyle)(this["StyleCombo1"]));
            }
            set {
                this["StyleCombo1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::MetroFramework.MetroColorStyle StyleCombo2 {
            get {
                return ((global::MetroFramework.MetroColorStyle)(this["StyleCombo2"]));
            }
            set {
                this["StyleCombo2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::MetroFramework.MetroThemeStyle Theme {
            get {
                return ((global::MetroFramework.MetroThemeStyle)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::MetroFramework.MetroThemeStyle ThemeTab {
            get {
                return ((global::MetroFramework.MetroThemeStyle)(this["ThemeTab"]));
            }
            set {
                this["ThemeTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Combo1 {
            get {
                return ((int)(this["Combo1"]));
            }
            set {
                this["Combo1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Combo2 {
            get {
                return ((int)(this["Combo2"]));
            }
            set {
                this["Combo2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int TrackBarVal {
            get {
                return ((int)(this["TrackBarVal"]));
            }
            set {
                this["TrackBarVal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::MetroFramework.MetroThemeStyle TrackBarTheme {
            get {
                return ((global::MetroFramework.MetroThemeStyle)(this["TrackBarTheme"]));
            }
            set {
                this["TrackBarTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::MetroFramework.MetroThemeStyle MetroLink1Theme {
            get {
                return ((global::MetroFramework.MetroThemeStyle)(this["MetroLink1Theme"]));
            }
            set {
                this["MetroLink1Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::MetroFramework.MetroThemeStyle MetroLink2Theme {
            get {
                return ((global::MetroFramework.MetroThemeStyle)(this["MetroLink2Theme"]));
            }
            set {
                this["MetroLink2Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string LabelVal {
            get {
                return ((string)(this["LabelVal"]));
            }
            set {
                this["LabelVal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PassLenght {
            get {
                return ((int)(this["PassLenght"]));
            }
            set {
                this["PassLenght"] = value;
            }
        }
    }
}
